Update post-install script
Moved to using a custom profile for the SITE or GROUP Token.

diff --git a/kandji/sentinel one/post-install script b/kandji/sentinel one/post-install script
--- a/kandji/sentinel one/post-install script
+++ b/kandji/sentinel one/post-install script
@@ -1,17 +1,20 @@
 #!/bin/bash
-
+#
 # Define the registration token
-SITE_TOKEN="YOUR_SITE_TOKEN_HERE"
-
+#SITE_TOKEN="YOUR_SITE_TOKEN_HERE"
+#
 # Create the registration token file
-echo "$SITE_TOKEN" > /tmp/sentinel_install/com.sentinelone.registration-token
-if [ $? -ne 0 ]; then
-    echo "Error: Failed to create registration token file."
-    exit 1
-fi
+#echo "$SITE_TOKEN" > /tmp/sentinel_install/com.sentinelone.registration-token
+#if [ $? -ne 0 ]; then
+#    echo "Error: Failed to create registration token file."
+#    exit 1
+#fi
+
+# Find the SentinelOne package
+pkg_file=$(find /tmp/sentinel_install/ -type f -name "Sentinel-Release-*.pkg" | head -n 1)
 
 # Install the SentinelOne package
-/usr/sbin/installer -pkg /tmp/sentinel_install/sentinel-installer.pkg -target /
+/usr/sbin/installer -pkg "$pkg_file" -target /
 if [ $? -ne 0 ]; then
     echo "Error: Failed to install the SentinelOne package."
     exit 1
